unclassified:
  artifactoryBuilder:
    artifactoryServers:
      - serverId: 'javaci2'
        artifactoryUrl: '${ARTIFACTORY_URL}'
        deployerCredentialsConfig:
          username: '${ARTIFACTORY_USER}'
          password: '${ARTIFACTORY_PASSWORD}'