credentials:
    system:
        domainCredentials:
        - domain:
              name: "(global)"
              description: "wildcard domain"
              specifications:
              - hostnameSpecification:
                    includes: "*"
          credentials:
          - usernamePassword:
                id: "575c7586-9870-40ad-927a-436f4a04ee51"
                scope: GLOBAL
                username: "software/rkusmierek"
                password: "secret"
                description: "Username/Password Credentials for software/rkusmierek"
