credentials:
    system:
        domainCredentials:
        - domain:
              name: "(global)"
              description: "wildcard domain"
              specifications:
              - hostnameSpecification:
                    includes: "*"
          credentials:
          - usernamePassword:
                id: "171b91f7-f868-4cb5-91d9-36007098f645"
                scope: GLOBAL
                username: "software/rkusmierek"
                password: "secret"
                description: "Username/Password Credentials for software/rkusmierek"
          - usernamePassword:
                id: "44ff692f-624a-4c6b-95cd-61eb6a8b9fe0"
                scope: GLOBAL
                username: "software/rkusmierek"
                password: "secret"
                description: "Username/Password Credentials for software/rkusmierek"
          - usernamePassword:
                id: "575c7586-9870-40ad-927a-436f4a04ee51"
                scope: GLOBAL
                username: "software/rkusmierek"
                password: "secret"
                description: "Username/Password Credentials for software/rkusmierek"
