tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  jdk:
    installations:
    - home: "/opt/jdk1.8.0_201"
      name: "jdk1.8.0_201"
    - home: "/usr/lib/jvm/java-8-openjdk-amd64"
      name: "jdk1.8.0_181"
    - home: "/opt/jdk1.8.0_201"
      name: "jdk8"
  maven:
    installations:
    - name: "Maven 3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.3.1"